CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE SCHEMA IF NOT EXISTS pavel_ovsyannikov;
SET search_path TO pavel_ovsyannikov, public;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL UNIQUE,
    password_hash text NOT NULL
);
CREATE TABLE specialists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
CREATE TABLE services (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0)
);
CREATE TABLE specialist_services (
    specialist_id bigint NOT NULL REFERENCES specialists,
    service_id bigint NOT NULL REFERENCES services,
    PRIMARY KEY (specialist_id, service_id)
);
CREATE TABLE slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_id bigint NOT NULL REFERENCES specialists,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    CHECK (ends_at > starts_at),
    UNIQUE (id, specialist_id)
);
CREATE TABLE appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users,
    specialist_id bigint NOT NULL REFERENCES specialists,
    service_id bigint NOT NULL REFERENCES services,
    slot_id bigint NOT NULL,
    status text NOT NULL CHECK (status IN ('booked', 'cancelled')),
    created_at timestamptz NOT NULL DEFAULT now(),
    cancelled_at timestamptz,
    FOREIGN KEY (slot_id, specialist_id) REFERENCES slots(id, specialist_id),
    FOREIGN KEY (specialist_id, service_id) REFERENCES specialist_services,
    CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL))
);
CREATE TABLE sessions (
    id text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL CHECK (expires_at > created_at)
);
